source 'https://rubygems.org'
ruby "2.1.2"

gem 'sinatra', '1.1.0'
gem 'eventmachine', '1.0.0.rc.1'
gem 'thin'
gem 'soap4r-ng'
gem 'rforce'
gem 'facets', '2.8.4'
gem 'hpricot'
gem 'json'
gem 'savon'
gem 'pg'
gem 'rack-ssl-enforcer'
gem 'rack-timeout'
