source 'https://rubygems.org'
ruby "2.5.7"

gem 'sinatra'
gem 'eventmachine'
gem 'thin'
gem 'soap4r-ng'
gem 'rforce'
gem 'facets'
gem 'hpricot'
gem 'json'
gem 'savon'
gem 'pg'
gem 'rack-ssl-enforcer'
gem 'rack-timeout'
gem 'httpclient'